name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  DOCKERHUB_USERNAME: tkreind

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test build
        run: |
          docker pull tkreind/massif-visualizer-novnc:latest
          docker build --cache-from tkreind/massif-visualizer-novnc:latest . --file Dockerfile


  push_to_registry:
    # Use CI environment secrets
    environment: "Continuous Integration"

    # Ensure test job passes before pushing image.
    needs: test
    
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${#DOCKERHUB_USERNAME}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,tkreind/massif-visualizer-novnc:latest
          cache-to: type=inline
          tags: tkreind/massif-visualizer-novnc:latest
